apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: nginx-isolation
  namespace: nginx-example
spec:
  description: "Allow nginx traffic only from ingress entity and DNS egress"
  endpointSelector:
    matchLabels:
      app: nginx
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
  egress:
    - toEntities:
        - world
    - toEndpoints:
        - matchLabels:
            k8s:k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
